### ISSUE TITLE
Set global defaults

### ISSUE THREAD

**Issue by squishram** [DavidAnson/markdownlint#1029]
Hi, thanks for your work on markdownlint. I am trying to disable one of the rules as a global default (MD013, which I find to be too opinionated for markdown). I don't want to have to disable it on a per-project basis in every single directory that includes .md files. I can't figure out how to make alterations to the global defaults for markdownlint - is there any way to do this? Ideally I would like to just put a config file in the right place for it to apply any edits to the defaults across my whole system. Thank you so much!

**Comment by DavidAnson** [comment]
It sounds like you are using one of the CLI tools instead of using this library directly. Neither CLI supports global configuration. However, you shouldn't need to put a configuration file in every directory, either. One configuration file located at the root of each project should be sufficient. This gives each project a single location to look for configuration and ensures that everybody working on that project has the same set of rules (versus if everyone had their own custom global configuration).
