### ISSUE TITLE
New Table formatting rule

### ISSUE THREAD

**Issue by gabriel-check24** [DavidAnson/markdownlint#1039]
I'd like to contribute a table formatting rule. The code I currently have will fix #90, #93, #132.
I'm creating this issue to both collect all table related issues (#92, #323) in one place and to secure a rule number.
Can I use Number 55?

`rules.js` contains 
`// md055: See https://github.com/markdownlint/markdownlint`
I haven't found an issue mentioning MD055 though.

**Comment by DavidAnson** [comment]
The Ruby implementation added three rules for tables recently and what you see are the placeholders I added. You can read more at the bottom here: <https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md>. They immediately got issues which have not been addressed as far as I know.

What you propose here is likely to be a very big undertaking. Someone else recently added a rule and I spent about a week reviewing and two weeks polishing, so anything here isn't going to make the current release.

Please read the contributing guidelines first so you know what's expected. For things that rely on a parser, please use the micromark tokens as that's the new direction. Adhere to the GFM standard for table syntax. I'll warn you that I will be very picky on the review.

One consideration is whether this should be one overall rule or multiple individual rules. Historically, specific individual rules has been the practice. If you are implementing an identical rule, please use the same name and number. Otherwise, please take the next consecutive number.

I'll want very good test coverage to try to avoid surprises. I anticipate a lot of edge cases here.

**Comment by gabriel-check24** [comment]
Thanks for the info, I did not check the ruby implementation.

> They immediately got issues which have not been addressed as far as I know.

Could you please add MD055, MD056 and MD057 to the respective issue title? This would make searching for them easier.
I think MD55 corresponds to #93 and MD056 to #92. 

My work so far was based on the GFM standard, so I should be able to reuse that. 
I wasn't sure whether to make individual rules or one for table formatting, but that clears it up,
I'll split into MD055, MD056 and make #132 MD058 then.

Understandable, please do address any issues, I'll run my code against our codebase, too.
Some edge cases are already filtered out by the parser, anything not recognized as a table won't make it to the rule. For the rest, I'll try to add extensive tests.

**Comment by DavidAnson** [comment]
I'll update the issue titles later today. But wanted to emphasize the last thing you said which is that sticking to scenarios the parser recognizes will make things much easier. Rules that try to infer intent outside of what parses successfully tend to be very tricky to get right.

**Comment by DavidAnson** [comment]
MD055 (and MD056) are in library version v0.33.0.
