### ISSUE TITLE
MD055/56 Don't properly handle pipes in content

### ISSUE THREAD

**Issue by kingthorin** [DavidAnson/markdownlint#1123]
This is two columns, the rules believe it is 6:

```md
| DBMS       | SQL Injection                                                         |
|------------|-----------------------------------------------------------------------|
| PostgreSQL | `$$='$$=chr(61)|| chr(0x27) and 1=pg_sleep(2)|| version()'`           |

```

**Comment by DavidAnson** [comment]
According to the GFM specification, pipes with a cell must be escaped - including those within inline spans such as code spans as used by your example. Because there is no escaping in your example, the parser treats each of those pipes as a delimiter and produces six cells. I believe this is correct.

Example 200 of the specification explicitly covers this scenario:
https://github.github.com/gfm/#example-200

**Comment by DavidAnson** [comment]
You can see in this Gist that GitHub does not render the table as you intend:
https://gist.github.com/DavidAnson/71ff1cb82d2004c57ef69a256b924048

**Comment by kingthorin** [comment]
Unfortunately in this case we don't care about eh GH rendering it's the deployment that mattes. I guess I'll have to annotate it to disable the rule or something.

![image](https://github.com/DavidAnson/markdownlint/assets/7570458/c9ea0145-c55a-4693-a333-d0e8e62550e5)
