### ISSUE TITLE
Include additional schema/types for strict rule name verification

### ISSUE THREAD

**Issue by regseb** [DavidAnson/markdownlint#1248]
If the configuration contains an unknown rule: Markdownlint must report that the rule isn't supported.

For example, ESLint reports the error: _Definition for rule 'no-konsole' was not found._

7 years ago, I misspelled the [`commonds-show-output`](https://github.com/regseb/castkodi/blame/v7.9.0/.metalint/markdownlint.config.js#L22) rule. And I've just realized it, thanks to a spellchecker that reported that the word _commonds_ doesn't exist.

**Comment by DavidAnson** [comment]
This has come up before, though I can’t find the discussion. Basically, because custom rules (like the one you are using) exist, there is no definitive list of valid rules they could appear in configuration. There IS a schema for configuration files and I have instructions for how to use it generally as well as how to identify non-core rules here: <https://github.com/DavidAnson/markdownlint/blob/main/schema/ValidatingConfiguration.md>

But I do not think it is appropriate to throw an error just because a configured rule does not happen to be in use at the moment. That same configuration file could be used across multiple runs of the tool and some of those runs may include or exclude various rules. It’s not wrong to configure a rule that isn’t in use, though I understand why you would have liked to be alerted in this scenario.

I’m open to suggestions, but think that validating with a schema as above is a reasonable approach.

**Comment by regseb** [comment]
You could provide two schemas: the current [`markdownlint-config-schema.json`](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/schema/markdownlint-config-schema.json) and the new `markdownlint-config-strict-schema.json` which is the same schema, but with `“additionalProperties”: false`. And export a new type `ConfigurationStrict` which is type [`Configuration`](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/lib/configuration.d.ts) without `[k: string]: unknown`.

With this solution, I can detect my problem with the JSDoc `/** @type {import("markdownlint").ConfigurationStrict} */` and TypeScript.
