### ISSUE TITLE
Allow Consecutive GitHub Alerts

### ISSUE THREAD

**Issue by gabeseltzer** [DavidAnson/markdownlint#1419]
GitHub uses the following syntax for ["Alerts"](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts):

```markdown
> [!NOTE]
> Useful information that users should know, even when skimming content.
```

If you put two alerts consecutively like this, you get a warning about: `MD028/no-blanks-blockquote: Blank line inside blockquote`

```markdown
> [!NOTE]
> my first note.

> [!NOTE]
> A second, consecutive note...
```

Can we change the parsing for the rule so that it recognizes the kinds of alerts and allows spaces between them?

**Comment by DavidAnson** [comment]
The rule documentation explains that this scenario is reported as a violation because some parsers combine consecutive blockquotes into one. That is not what the CommonMark specification says to do and it's not what GitHub does for blockquotes, but it can be a problem. I don't think this situation is unique to GitHub Alerts and I'd recommend disabling the rule if you're only authoring for GitHub.

https://github.com/DavidAnson/markdownlint/blob/main/doc/md028.md
