### ISSUE TITLE
MD004 and TaskList

### ISSUE THREAD

**Issue by HBSpy** [DavidAnson/markdownlint#173]
Any idea to deal with Extended Syntax Task List?
- [x] Write the press release
- [ ] Contact the media
- [ ] Update the website

now it will alert MD004

**Comment by DavidAnson** [comment]
The style GitHub uses seems not to trigger any MD004 errors: 
https://guides.github.com/features/mastering-markdown/

Could you please show some example Markdown or link to a document with violations?

**Comment by HBSpy** [comment]
I found it in my VS Code

![TIM截图20190320092111](https://user-images.githubusercontent.com/3386804/54652402-bbcf2780-4af1-11e9-950e-5111d818a2f8.png)
![TIM截图20190320092147](https://user-images.githubusercontent.com/3386804/54652406-bd98eb00-4af1-11e9-89c8-e0041d095eec.png)

**Comment by DavidAnson** [comment]
That’s because an earlier list in your document (the one at the top of your image) uses the ‘*’ as a list marker. By default, MD004 assumes the first list item it finds uses the list marker style you want for the entire document. You could change the other list(s) to use ‘-‘ and this warning should go away. Or you could disable MD004 if you like how your document is now.

More info here: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md004

**Comment by HBSpy** [comment]
O, i see
I prefer to use * for list and - [x] for task 
THX
