### ISSUE TITLE
MD025 conflicts with hexo 

### ISSUE THREAD

**Issue by MisakaMikoto19090** [DavidAnson/markdownlint#177]
MD025 used to work fine with my hexo blogs. today there is a warning .

Is this a bug? Or is there a way to disable MD025.

![Annotation 2019-04-11 111844](https://user-images.githubusercontent.com/10293827/55928647-1c163c80-5c4c-11e9-9e97-0bed3bc53c1d.png)

**Comment by DavidAnson** [comment]
This seems like a bug fix. :) MD025 reports a violation when there are multiple top level headings (usually h1) in a document. You have one of those on line 13.  What’s new is that “title“ properties in YAML front matter are also treated like a top level heading because most blog engines use those as the title. You can disable the new behavior by customizing the rule. This is discussed more in the documentation: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#

Hope this helps!

**Comment by MisakaMikoto19090** [comment]
thank you very much for your time.I should have check the doc first.
