### ISSUE TITLE
rule MD034 flags URL in `Inline code` with backticks as "bare url"

### ISSUE THREAD

**Issue by xueqing** [DavidAnson/markdownlint#181]
A URL inside of an `inline code` with backticks is marked as a "bare url" by markdownlint.
My editor is vscode.

Example:
`git clone https://github.com/tensorflow/tensorflow.git`

![markdownlint-no-bare-urls](https://user-images.githubusercontent.com/6188285/56857534-43397180-69a1-11e9-90cb-34aa6b8555ec.png)

**Comment by DavidAnson** [comment]
Thanks, I should be able to look at this soon.

**Comment by nschonni** [comment]
I think it's actually flagging the `# use https://`, but I've noticed that the cursor position can sometimes be off on rules in VS Code. EX: Unescaped (MD033) violations usually point to the first element on a line, even if the actual error is with a different element later on in the same line.

**Comment by xueqing** [comment]
Thank you for your explanation! It works for me.

**Comment by xueqing** [comment]
It seems it's my comment problem o(╥﹏╥)o
@DavidAnson

**Comment by DavidAnson** [comment]
That’s great to know, thank you both! I think the error and line number are correct, but the highlighting is wrong. I will leave this issue open to look into that.

Some background, in case you are interested: Some rules identify the range themselves and should usually be correct. There are some cases where the VS Code extension does its own range calculation and those are less reliable because they are based on regular expressions.

**Comment by DavidAnson** [comment]
By the way, I am one failing a test case away from improving MD033 in an upcoming commit. It should handle a few more scenarios and highlight better very soon!
