### ISSUE TITLE
MD036 is not support the punctuation '。'

### ISSUE THREAD

**Issue by ukipoi** [DavidAnson/markdownlint#192]
'。' is a punctuation in Chinese like '.' in English.
I hope the new version supports this punctuation.

**Comment by DavidAnson** [comment]
> The issue title says MD036, but I think you mean MD026, right?

The `punctuation` parameter of MD026 already lets you change the list of characters: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md026

Example: https://github.com/DavidAnson/markdownlint/blob/2710c375b3c9b9b6531d546b667f50f7d0c956f2/test/heading_trailing_punctuation_customized.json

However, if this is a common punctuation character in Chinese, I don’t mind adding it to the default list. To do so, I would need some example text to create the test case from. If you want, please include some examples here. Otherwise, I will close this issue because it is already supported.

Thank you!

**Comment by DavidAnson** [comment]
More info here: https://en.wikipedia.org/wiki/Chinese_punctuation

It looks like each of the 6 current default punctuation characters have a corresponding full-width representation that could be added.

**Comment by TheDauntless** [comment]
The same period is used in Japanese. You can find a test-case here:

https://github.com/OWASP/owasp-masvs/blob/master/Document-ja/0x03-Using_the_MASVS.md

I'll try adding the period myself for now.
