### ISSUE TITLE
MD046 flagged when html comment in list item as string

### ISSUE THREAD

**Issue by nschonni** [DavidAnson/markdownlint#202]
OK, I can't seem to get a minimum reproduction, but I hit it in this file https://github.com/MicrosoftDocs/visualstudio-docs/blob/3375c14411efb46b62c594fa5d504be9a0fcd5f8/docs/xml-tools/walkthrough-using-xml-editor-features.md
The following section and the final H2 get flagged with the rule 
```md
2. Select **<!--** to add a comment node and press **Enter**.

     The editor inserts a comment end tag and places the cursor between the start and end comment tags.
```
This doesn't reproduce on your demo site with just the snippet, so I think there is a larger edge case I'm not seeing.
I can resolve it if I change `<!--` to `&lt;--`, so it is probably somewhere in the HTML comment handling

**Comment by DavidAnson** [comment]
Thanks for trying! I’ll have a look in a couple of weeks when I circle back to this project.

**Comment by DavidAnson** [comment]
I’m not able to reproduce this so far. That start-comment marker is recognized as beginning a comment, so the content after gets ignored. This is intentional and consistent with HTML. Given the uniqueness of this scenario and the workaround you propose, I’m not sure it’s worth spending too much more time here.
