### ISSUE TITLE
<br> in table triggers MD33

### ISSUE THREAD

**Issue by darkantoine** [DavidAnson/markdownlint#214]
We use <br> inside table to spreads the description in a cell over several lines to add readibility.
This triggers MD33 but I dont think it should.

**Comment by DavidAnson** [comment]
It sounds like you think the rule is behaving as described, but don’t like that behavior in your scenario? If so, you can disable `MD033` entirely or use the `allowed_elements` parameter to exempt just the `br` tag.

**Comment by DavidAnson** [comment]
Closing as it seems the original and related questions are both addressed.

**Comment by afeblot** [comment]
@DavidAnson , I find myself in the same situation where I have MD033 enabled and currently only allowing `<br/>` tags because I consider them needed in tables. However, I'd be happy to forbid them elsewhere.

If I succeed submitting a PR adding a "allowed_in_tables" option to MD033, will you consider it for merge?

**Comment by afeblot** [comment]
https://github.com/DavidAnson/markdownlint/pull/1615
