### ISSUE TITLE
Fix is not fixing line_length 

### ISSUE THREAD

**Issue by wtrocki** [DavidAnson/markdownlint#294]
```
{
    "line_length": 120
}
```

markdownlint ./docs/**/*.md --fix

Getting issues about lines but they aren't fixed

**Comment by DavidAnson** [comment]
Not all rules are fixable. I have a note to call this out explicitly in the rule documentation, but for now you can find a list here: https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#rules

In particular, line length is not automatically fixed because there are many cases where it won’t be clear to a tool what to change to reflow a paragraph, etc.. This is a feature many editors support and I recommend addressing line length issues that way.

**Comment by DavidAnson** [comment]
Fixable rules are now called out in the documentation by https://github.com/DavidAnson/markdownlint/commit/53a0ba18d847cd49952f5626ac700189a821ce99 for the next release.

**Comment by virtzilla** [comment]
It would be incredibly useful to show in the output of the command (i.e. a prefix or suffix of "NOT FIXED" or "CAN'T FIX") on what isn't fixed rather than having to hunt down in the documentation to find it's behaving as designed and it's not a bug that it didn't fix it (after trying repeatedly way more times than I care to admit).
