### ISSUE TITLE
Regarding MD026 No Trailing Punctuation

### ISSUE THREAD

**Issue by jamesmrollins** [DavidAnson/markdownlint#364]
Hi @DavidAnson 
I am attempting to follow code directions to allow exclamation points in headings.  According to what I read, the code snippet in the markdownlint.json, shown below, should screen for periods, commas, semicolons and colons only:

"MD026": { "level" : ".,;:" }

![image](https://user-images.githubusercontent.com/30132017/103811276-87539500-5011-11eb-9f6a-0b14d50f657b.png)

When I run the linter it still calls out the exclamation points as an error.  

Thank you in advance,
James

**Comment by DavidAnson** [comment]
The parameter name is `punctuation`, not `level`.

https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md026

**Comment by waldyrious** [comment]
This issue is similar to #276, which requested to allow `?` in headings. I can see a similar reason to allow `!` as well — I've seen e.g. FAQ documents that add exclamations alongside questions, and can also think of a step-by-step guide whose last section could be something like "That's it!", etc.

By this reasoning, the final period should also be allowed. Alternatively, these end-of-sentence punctuation marks (`.`, `!` and `?`, and their fullwidth variants) could be bundled into a possible configuration of the `no-trailing-punctuation` rule.

**Comment by DavidAnson** [comment]
@waldyrious The issue here was misconfiguration and I'll close it if resolved. Regarding other punctuation, there will always be exceptions. This rule can be disabled or customized when needed. The only feedback that seemed consistent was question mark.

**Comment by DavidAnson** [comment]
MD026 looks to be used about 87% of the time, so I'm not ready to remove or disable it just yet.

https://dlaa.me/blog/post/markdownlintanalyzeconfig

**Comment by jamesmrollins** [comment]
@DavidAnson -  Yes, this issue was resolved by using the correct parameter.  Thank you for the very prompt assistance.  James
