### ISSUE TITLE
[Discussion] contributes to `remark-lint` instead

### ISSUE THREAD

**Issue by JounQin** [DavidAnson/markdownlint#378]
like `JSCS` to `ESLint`

1. [`remark-lint`](https://github.com/remarkjs/remark-lint) is much more pluggable than `markdownlint`.
2. It can be integrated with `eslint` via [`esling-plugin-mdx`](https://github.com/mdx-js/eslint-mdx#mdxremark) (Don't worry, markdown is also supported).
3. It will never conflict with `prettier` via [`remark-preset-prettier`](https://github.com/JounQin/remark-preset-prettier)

**Comment by DavidAnson** [comment]
I would encourage everyone to use and contribute to whatever projects they feel meet their needs best - and it seems remark is a fine project. That said, the experience I get working on markdownlint is valuable to me and I would probably do so even if nobody used it. Therefore, I will close this issue because I do not think there is much to discuss; I will keep tinkering with this project and I encourage others to spend their time on whatever they think is most meaningful.

**Comment by JounQin** [comment]
That's OK, I just to discuss is that possible to merge these two projects, like `JSCS` and `ESLint`.

https://eslint.org/docs/user-guide/migrating-from-jscs

The users must choose between they, and there is much repetitive work in two projects.
