### ISSUE TITLE
Numbered Lists Throwing MD029 Violation

### ISSUE THREAD

**Issue by jamesmrollins** [DavidAnson/markdownlint#407]
Hi @DavidAnson 

I am curious why the lists as shown below are throwing a both a MD029 and a MD033 error and what the fixes could be?

- I thought if I indented the image link, that it would not interrupt the list continuity.
- This is the way to reference an image in a repository.  Is there something I am doing wrong? It seems to work. 

![image](https://user-images.githubusercontent.com/30132017/122479238-9276fd80-cf7f-11eb-9f0c-cf4f2ea89880.png)

**Comment by nschonni** [comment]
Items inside numbered lists need to be a minimum of 3 spaces for you screenshot (to match 3 characters before the "Click") https://spec.commonmark.org/0.29/#list-items

**Comment by DavidAnson** [comment]
One issue is that you are using HTML send text for the image instead of markdown syntax. That's why you're seeing MD033.

I think MD029 is coming about because the HTML syntax above breaks the list into two and so it complains that the "second" list is beginning with the number 2.

List item content should be indented to line up with the start of the first content after the list item marker. In the case of unordered lists, that is typically 2 spaces but in the case of ordered lists like this one, it is typically 3 spaces (or 4 for double-digit numbers).

I think switching to Markdown syntax for the image and indenting one more character will address the issues you describe.

**Comment by DavidAnson** [comment]
(Sorry, Nick, your reply came in as I was writing mine!)

**Comment by jamesmrollins** [comment]
Thank you both for the directions. I will try these out.
