### ISSUE TITLE
Update MD010/hard-tabs to allow configuring the number of spaces in a code block/fence

### ISSUE THREAD

**Issue by Stanzilla** [DavidAnson/markdownlint#416]
My `.markdownlint.json` config is as follows:

```json
{
    "default": true,
    "MD004": false,
    "MD013": false,
    "MD024": false,
    "MD025": { "level": 1, "front_matter_title": ""},
    "MD029": { "style": "ordered" },
    "MD007": { "indent": 4 },
    "MD046": false,
    "no-alt-text": true,
    "no-inline-html": false,
    "no-space-in-code": false,
    "code-block-style": false,
    "no-blanks-blockquote": false
}
```

Yet when I use quick fix to replace a hard-tab, it replaces it with 2 spaces instead of 4.

https://user-images.githubusercontent.com/75278/128001971-55a907c6-66ee-42ee-94eb-518d570763f3.mp4

**Comment by DavidAnson** [comment]
I think the `spaces_per_tab` parameter may already do what you want: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md010

**Comment by Stanzilla** [comment]
Oh interesting, thank you!

**Comment by nschonni** [comment]
I was thinking of opening a new issue, but I think it's still related to this one.
Usually inside a code fence a more sensible default would be 2 or 4 (the GitHub rendering default of 8 is too much). Maybe that requires a separate option than the current `spaces_per_tab` like `spaces_per_tab_in_code` (awkward name) or allowing the current `code_blocks` to use an integer for those spaces instead of the current boolean

**Comment by DavidAnson** [comment]
As this is closed, a new issue would be helpful!
