### ISSUE TITLE
hard-line break and users who forget to type the 2 spaces

### ISSUE THREAD

**Issue by LucianoBestia** [DavidAnson/markdownlint#421]
Thank you for markdownlint. It is great, a lifesaver!

I always use 2 spaces at the end of a paragraph for `hard-line break`.
But sometimes I forget to type them. And I don't observe this error until I push to Github.
Is it possible to have a lint to show where I forgot to put the 2 spaces?  
Except in code segments or lists, I think that most users want to have always 2 spaces before an LF.  
Sure somebody likes to use \ (backslash) and he should have the possibility to disable this rule. Or maybe this rule could check also for that syntax for `hard-line break`.

**Comment by DavidAnson** [comment]
I think for most people 2 spaces is used rarely or never. Are you saying every paragraph in your file ends with 2 spaces? Is that to add extra space after the text? Could you do that with a style sheet instead?

**Comment by LucianoBestia** [comment]
Thank you. 
You made me think and I learned there exists (at least) 2 different line-breaks:
1. between paragraphs
2. inside a paragraph (hard line breaks)

(from https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#paragraphs):
**Paragraphs**
You can create a new paragraph by leaving a blank line between lines of text.

(from https://github.github.com/gfm/):
**6.12Hard line breaks**
A line break (not in a code span or HTML tag) that is preceded by **_two_** or more **_spaces_** and does not occur at the end of a block is parsed as a hard line break (rendered in HTML as a `<br />` tag)

I like the second one: `Hard line breaks` and I use them a lot.
I always write in editors that have word-wrap, so I never put a LF (line-break) in between my sentences.
I believe many developers use word-wrap editors too.
And for that type of use every newline is meant to be space+space+newline.
Except inside a code block.

Some discussion about space+space+newline:
https://stackoverflow.com/questions/24575680/new-lines-inside-paragraph-in-readme-md
https://gist.github.com/shaunlebron/746476e6e7a4d698b373

I thought that everybody is doing space+space for line breaks.
But I see there are different approaches. 
I looked at your README.md and I see you use line-breaks to make lines shorter. 
It looks like a `manual word-wrap`. 
Correct me if I saw it wrong. Text rendering can be very different from editor to editor.

![image](https://user-images.githubusercontent.com/31509965/130183317-31cd80f9-edf4-4c6a-afc6-55c6db2f4a34.png "text")

**Comment by DavidAnson** [comment]
When I am writing a blog post that people will only ever see as HTML, I write the Markdown with one sentence per line. So a paragraph with five sentences will be five lines and each of those lines will have different lengths. This is a pretty easy style to write with because I don't need to worry much about wrapping and also because it behaves reasonably for diff in git.

For something like a README, where people will also be looking at the file in text form, I will tend to manually wrap lines at around 80 columns. (Rule MD013 helps with this.) In most editors, this formatting is a manual process and it is kind of annoying to do, but it produces text that is easily read by someone else in any viewer without worrying about scrolling, wrapping, etc.. (Some editors will do this wrapping for you, but not the ones I use.)

Hard line breaks are meant to be a special case for scenarios where the Markdown language doesn't automatically do the right thing. But most of the time it's smart enough to produce good looking output based on the structure of its input.

**Comment by LucianoBestia** [comment]
Thank you. 
Now I understand better the nuances of the newline in markdown. It is used in many different ways that I didn't know about.

Just for the completeness of the discussion if somebody will read this:
Some other "languages" use the opposite approach: "Line continuation character".
The line continuation character in JavaScript is the backslash.
<https://bettersolutions.com/javascript/syntax/line-continuation-character.htm>
``` javascript
var mystring = 'this is my \  
      'string that spans \
      'three lines';
```

<https://python-reference.readthedocs.io/en/latest/docs/operators/slash.html>
```python
>>> if 1900 < year < 2100 and 1 <= month <= 12 \
... and 1 <= day <= 31 and 0 <= hour < 24 \
... and 0 <= minute < 60 and 0 <= second < 60:   # Looks like a valid date
...     return 1
```
