### ISSUE TITLE
MD029 numbers over "100"

### ISSUE THREAD

**Issue by telekomancer** [DavidAnson/markdownlint#446]
Hi i have a problem with linting:

![image](https://user-images.githubusercontent.com/27900350/138004646-75c827da-78fa-4c19-a707-2e2ba4f4b502.png)

This happen on VSCode i havent versions but this is the only info that i have:

![image](https://user-images.githubusercontent.com/27900350/138004761-27692669-3ec5-41b8-a9dc-22c9dc5140dc.png)

**Comment by DavidAnson** [comment]
My guess is that whatever is on line 517 is ending the first ordered list. Text or a comment would do that.

**Comment by DavidAnson** [comment]
The content in item 100 (and later) needs to be indented an additional space in order to start in the proper column. As written, it's doing the equivalent of this which ends the first list: https://markdown-it.github.io/#md3=%7B%22source%22%3A%221.%20Text%5Cn%5Cn%20%20%20Text%5Cn%5Cn2.%20Text%5Cn%5Cn%20%20Text%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

**Comment by telekomancer** [comment]
Uncomfortable, but pretty simple solution.

Thanks for your support @DavidAnson .

Warms!
