### ISSUE TITLE
suggestion; allow 2 consecutive blank lines in front of headings

### ISSUE THREAD

**Issue by Reissner** [DavidAnson/markdownlint#503]
Maybe a good idea to make configurable: 
allow 2 blank lines in front of headings. 
In this case, the 2 blank lines serve a goal: improve readability.

**Comment by DavidAnson** [comment]
MD022 supports a `lines_above` which should do what you want.

https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md022

**Comment by lud** [comment]
Generally my manual formatting goes this way:

* two blank lines above `h2`
* one blank line above `h3` or lower
* one blank line below all headings

Thanks to that the visual separation of the mains sections of the text is more obvious.

Is that something that markdownlint could enforce or do you think it is too specific?

**Comment by DavidAnson** [comment]
That's pretty specialized, but I could imagine adding a property to the existing rule that let you set the number of lines above and below each heading level. That would allow you to require the behavior you want - as well as anything else. I'd want to track this request as a new "enhancement" issue, rather than with this one, so please open it if you'd like.
