### ISSUE TITLE
MD013 line length rule is enforced in github action and not in vscode   

### ISSUE THREAD

**Issue by satanshiro** [DavidAnson/markdownlint#909]
running the vscode markdown lint extension does not recognize MD013 violations (with or without word wrap enabled in vs code)
but the github action does recognize the violation.
I have no idea why this is happening.
running the vscode :
![image](https://github.com/DavidAnson/markdownlint/assets/38865738/f9cb7dd8-f0be-4c26-8271-ceda911f00c5)
also does not yield line lengh error
am I the only one?

**Comment by satanshiro** [comment]
so not sure if this needs to be closed and if it's on purpose but not sure why default configurations differ from the cli and the extension

**Comment by DavidAnson** [comment]
Yes, the line length rule is disabled (and documented) by default in the VS Code extension because long lines are common and many people edit files and projects that are not configured for markdownlint and otherwise they would see squiggly underlining for every line in every Markdown file that is longer than 80 characters. Anyone using the CLI or the library directly knows what they are doing and that they have the ability to disable rules and therefore all rules are on by default.

This behavior is intended and this issue can be closed. Thanks!
